"use client"
import "normalize.css";
import { Nunito_Sans } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { useEffect } from "react";
import Header from "./component/header";
import Footer from "./component/footer";





const nunitoSans = Nunito_Sans({
  weight: ['400', '600','700','800'],
  subsets: ["latin"],
  variable: "--font-nunito-sans",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  return (
    <html lang="fr">
        <head>
                 <link rel="icon" type="image/png" href="./anonym.png"></link>
            </head>
      
      <body className={`${nunitoSans.variable}`}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}


